runner:
  labels:
    - ubuntu-latest:docker://ghcr.io/ondrejbudai/podman-runner:latest

container:
  options: --cap-add=sys_admin,mknod --device=/dev/fuse --security-opt label=disable
  network: systemd-main
