runner:
  labels:
    - ubuntu-latest:docker://ghcr.io/ondrejbudai/podman-runner:2024-09-28

container:
  options: --security-opt seccomp=unconfined --device=/dev/fuse --security-opt label=disable
  network: systemd-main
